### ISSUE TITLE
Help me please with telescope-ui-select

### ISSUE THREAD

**Issue by MitaiDart** [JafarAbdi/myconfigs#41]
Hi, please help me configure the output of the `lua vim.lsp.buf.code_action()` command via telescope-ui, I copied part of your config, but I still output through the native module...
I'm new to Vim/Neovim and I don't understand everything, I'm sorry if my question is stupid
![Снимок экрана от 2022-11-23 13-15-39](https://user-images.githubusercontent.com/104931116/204151764-4207e11f-e233-49d0-8c5c-98abc0bd315f.png)
my config [https://gitflic.ru/project/dartmitai/neovim/blob?file=lua%2Fplugins%2Ftelescope.lua](url)

**Comment by JafarAbdi** [comment]
>  I'm new to Vim/Neovim and I don't understand everything, I'm sorry if my question is stupid

It's all good, we all were new at some point ;)

I'm closing this in favor of the one you opened in the upstream repo, btw, I can't access your dotfiles!
